import { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";
import * as THREE from 'three';
import TvScreenContent from "./TvScreenContent";
import useNavigation from "../hooks/useNavigation";
import { LAPTOP_CAMERA_VIEW } from "../constants";
import WorkEx from "./WorkEx";

function Laptop(props: any) {
    const laptopScreenRef = useRef<THREE.Mesh>(null);
    const { flyToLaptop } = useNavigation();
    // Load model
    const { nodes, materials } = useGLTF('Models/mac-draco.glb') as any

    function handleClick() {
        // Fly to the perfect laptop viewing angle
        flyToLaptop(
            LAPTOP_CAMERA_VIEW.position,
            LAPTOP_CAMERA_VIEW.target,
            LAPTOP_CAMERA_VIEW.rotation,
            1  // 1 second smooth animation
        );
    }

    // The jsx graph was auto-generated by: https://github.com/pmndrs/gltfjsx
    return (
        <group onClick={handleClick} {...props} dispose={null}>
            <group rotation-x={-0.425} position={[0, -0.04, 0.41]}>
                <group position={[0, 2.96, -0.13]} rotation={[Math.PI / 2, 0, 0]}>
                    <mesh material={materials.aluminium} geometry={nodes['Cube008'].geometry} />
                    <mesh material={materials['matte.001']} geometry={nodes['Cube008_1'].geometry} />
                    <mesh ref={laptopScreenRef} geometry={nodes['Cube008_2'].geometry}>
                        {/* Drei's HTML component can "hide behind" canvas geometry */}
                        <Html className="content" rotation-x={-Math.PI / 2} position={[0, 0.05, -0.09]} transform occlude>
                            <div onClick={handleClick} className="wrapper">
                                <WorkEx />
                            </div>
                        </Html>
                    </mesh>
                </group>
            </group>
            <mesh material={materials.keys} geometry={nodes.keyboard.geometry} position={[1.79, 0, 3.45]} />
            <group position={[0, -0.1, 3.39]}>
                <mesh castShadow receiveShadow material={materials.aluminium} geometry={nodes['Cube002'].geometry} />
                <mesh castShadow receiveShadow material={materials.trackpad} geometry={nodes['Cube002_1'].geometry} />
            </group>
            <mesh material={materials.touchbar} geometry={nodes.touchbar.geometry} position={[0, -0.03, 1.2]} />
        </group>
    )
}

export default Laptop;
