
import { useGLTF } from '@react-three/drei'

export default function Workspace(props: any) {
    const { scene } = useGLTF('/Models/gaming_raw3.glb') as any;
    const position = [-0.72, -2, 0];
    const rotation = [-0.35, -1.07, -0.04];
    const scale = 1.05;
    return (
        <group>
            <primitive object={scene} position={position} rotation={rotation} scale={scale} />
        </group>
        //     <group {...props} dispose={null}>
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plane004.geometry}
        //             material={materials['Material.001']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Base002.geometry}
        //             material={materials['Material.003']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Door.geometry}
        //             material={materials['Material.014']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Handle_1.geometry}
        //             material={materials['Material.011']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Legs003.geometry}
        //             material={materials['Material.002']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plastic.geometry}
        //             material={materials['Material.008']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Arm_Cushions.geometry}
        //             material={materials['Material.045']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.ArmHodlers.geometry}
        //             material={materials['Material.044']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Base001.geometry}
        //             material={materials['Material.043']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cushion_2.geometry}
        //             material={materials['Material.041']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Legs001.geometry}
        //             material={materials['Material.040']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Handel_Metal.geometry}
        //             material={materials['Material.012']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Pipes.geometry}
        //             material={materials['Material.038']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Pipes001.geometry}
        //             material={materials['Material.038']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Pipes002.geometry}
        //             material={materials['Material.038']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plastic_Screws.geometry}
        //             material={materials['Material.036']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Screws001.geometry}
        //             material={materials['Material.035']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.wheel_protectors.geometry}
        //             material={materials['Material.034']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.wheels.geometry}
        //             material={materials['Material.033']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Handel_Plastic.geometry}
        //             material={materials['Material.037']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cushion_1001.geometry}
        //             material={materials['Material.013']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plastic001.geometry}
        //             material={materials['Material.009']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plane002.geometry}
        //             material={materials['Material.090']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plane006.geometry}
        //             material={materials['Material.089']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plane007.geometry}
        //             material={materials['Material.087']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plane016.geometry}
        //             material={materials['Material.086']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Circle001.geometry}
        //             material={materials['Material.076']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Circle002.geometry}
        //             material={materials['Material.075']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Circle009.geometry}
        //             material={materials['Material.074']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube.geometry}
        //             material={materials['Material.073']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plane005.geometry}
        //             material={materials['Material.064']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Circle.geometry}
        //             material={materials['Material.078']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plane001.geometry}
        //             material={materials['Material.077']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube005.geometry}
        //             material={nodes.Cube005.material}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cable_1.geometry}
        //             material={materials['Material.085']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cable_2.geometry}
        //             material={materials['Material.084']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cable_3.geometry}
        //             material={materials['Material.083']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cable_4.geometry}
        //             material={materials['Material.082']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.NurbsPath001.geometry}
        //             material={materials['Material.080']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.NurbsPath.geometry}
        //             material={materials['Material.081']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.drawer.geometry}
        //             material={materials['Material.063']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Legs002.geometry}
        //             material={materials['Material.056']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plastic002.geometry}
        //             material={materials['Material.055']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.drawer001.geometry}
        //             material={materials['Material.062']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Bottom.geometry}
        //             material={materials.Material}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Scroll_Button.geometry}
        //             material={materials['Material.061']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Top.geometry}
        //             material={materials['Material.060']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plane012.geometry}
        //             material={materials['Material.057']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plane013.geometry}
        //             material={materials['Material.059']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube003.geometry}
        //             material={materials['Material.020']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Front.geometry}
        //             material={materials['Material.032']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Usb_metal.geometry}
        //             material={materials['Material.031']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Usb_plastic.geometry}
        //             material={materials['Material.030']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Holes.geometry}
        //             material={materials['Material.029']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Back.geometry}
        //             material={materials['Material.028']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Legs.geometry}
        //             material={materials['Material.047']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Metal.geometry}
        //             material={materials['Material.042']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Planks.geometry}
        //             material={materials['Material.048']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Screws.geometry}
        //             material={materials['Material.046']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Mug.geometry}
        //             material={materials['Material.049']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Pencile_cup.geometry}
        //             material={materials['Material.091']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Pencile_cup001.geometry}
        //             material={materials['Material.109']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Plane003.geometry}
        //             material={materials['Material.114']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube018.geometry}
        //             material={materials['Material.072']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube018_1.geometry}
        //             material={materials['Material.071']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube017.geometry}
        //             material={materials['Material.070']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube017_1.geometry}
        //             material={materials['Material.069']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube016.geometry}
        //             material={materials['Material.068']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube016_1.geometry}
        //             material={materials['Material.067']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube016_2.geometry}
        //             material={materials['Material.066']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube016_3.geometry}
        //             material={materials['Material.065']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube023.geometry}
        //             material={materials['Material.053']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube023_1.geometry}
        //             material={materials['Material.054']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube024.geometry}
        //             material={materials['Material.051']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube024_1.geometry}
        //             material={materials['Material.052']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder015.geometry}
        //             material={materials['Material.092']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder015_1.geometry}
        //             material={materials['Material.093']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder015_2.geometry}
        //             material={materials['Material.094']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder018.geometry}
        //             material={materials['Material.093']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder018_1.geometry}
        //             material={materials['Material.094']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder018_2.geometry}
        //             material={materials['Material.095']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder024.geometry}
        //             material={materials['Material.093']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder024_1.geometry}
        //             material={materials['Material.094']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder024_2.geometry}
        //             material={materials['Material.096']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder025.geometry}
        //             material={materials['Material.097']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder025_1.geometry}
        //             material={materials['Material.098']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube025.geometry}
        //             material={materials['Material.099']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube025_1.geometry}
        //             material={materials['Material.100']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube025_2.geometry}
        //             material={materials['Material.101']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube026.geometry}
        //             material={materials['Material.104']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube026_1.geometry}
        //             material={materials['Material.100']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube026_2.geometry}
        //             material={materials['Material.101']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube027.geometry}
        //             material={materials['Material.103']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube027_1.geometry}
        //             material={materials['Material.100']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube027_2.geometry}
        //             material={materials['Material.101']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube028.geometry}
        //             material={materials['Material.102']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube028_1.geometry}
        //             material={materials['Material.100']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube028_2.geometry}
        //             material={materials['Material.101']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube034.geometry}
        //             material={materials['Material.105']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube034_1.geometry}
        //             material={materials['Material.100']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube034_2.geometry}
        //             material={materials['Material.101']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube035.geometry}
        //             material={materials['Material.108']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube035_1.geometry}
        //             material={materials['Material.100']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube035_2.geometry}
        //             material={materials['Material.101']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube036.geometry}
        //             material={materials['Material.106']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube036_1.geometry}
        //             material={materials['Material.100']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube036_2.geometry}
        //             material={materials['Material.101']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube037.geometry}
        //             material={materials['Material.107']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube037_1.geometry}
        //             material={materials['Material.100']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cube037_2.geometry}
        //             material={materials['Material.101']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder027.geometry}
        //             material={materials['Material.111']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder027_1.geometry}
        //             material={materials['Material.093']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder027_2.geometry}
        //             material={materials['Material.094']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder028.geometry}
        //             material={materials['Material.093']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder028_1.geometry}
        //             material={materials['Material.094']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder028_2.geometry}
        //             material={materials['Material.113']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder029.geometry}
        //             material={materials['Material.093']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder029_1.geometry}
        //             material={materials['Material.094']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder029_2.geometry}
        //             material={materials['Material.112']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder030.geometry}
        //             material={materials['Material.110']}
        //         />
        //         <mesh
        //             castShadow
        //             receiveShadow
        //             geometry={nodes.Cylinder030_1.geometry}
        //             material={materials['Material.098']}
        //         />
        //     </group>
    )
}

useGLTF.preload('/Models/wrokspace.glb')

